{
  "uid" : "15d8c067758d6dfd",
  "name" : "test_browsesVlog",
  "fullName" : "test_011_browsesVlog.Test_browsesVlog#test_browsesVlog",
  "historyId" : "58a35e78c95610b9a2577f96444cd07a",
  "time" : {
    "start" : 1587462743372,
    "stop" : 1587462796321,
    "duration" : 52949
  },
  "status" : "passed",
  "flaky" : true,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "passed",
    "steps" : [ {
      "name" : "点击sVlog标题",
      "time" : {
        "start" : 1587462743372,
        "stop" : 1587462771025,
        "duration" : 27653
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false,
      "stepsCount" : 0
    }, {
      "name" : "浏览长视频列表",
      "time" : {
        "start" : 1587462771025,
        "stop" : 1587462786247,
        "duration" : 15222
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false,
      "stepsCount" : 0
    }, {
      "name" : "断言:无任何崩溃闪退",
      "time" : {
        "start" : 1587462786247,
        "stop" : 1587462796321,
        "duration" : 10074
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false,
      "stepsCount" : 0
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true,
    "stepsCount" : 3
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "suite",
    "value" : "test_011_browsesVlog"
  }, {
    "name" : "subSuite",
    "value" : "Test_browsesVlog"
  }, {
    "name" : "host",
    "value" : "PV-X00232293"
  }, {
    "name" : "thread",
    "value" : "40208-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test_011_browsesVlog"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "130d6fea217ce03c",
      "status" : "passed",
      "time" : {
        "start" : 1587459321964,
        "stop" : 1587459365480,
        "duration" : 43516
      }
    }, {
      "uid" : "ec5288900bb03492",
      "status" : "passed",
      "time" : {
        "start" : 1587261631392,
        "stop" : 1587261671158,
        "duration" : 39766
      }
    }, {
      "uid" : "287acc55de6a23a0",
      "status" : "passed",
      "time" : {
        "start" : 1587259934077,
        "stop" : 1587260015397,
        "duration" : 81320
      }
    }, {
      "uid" : "16649d28f3a22476",
      "status" : "passed",
      "time" : {
        "start" : 1587153779683,
        "stop" : 1587153832313,
        "duration" : 52630
      }
    }, {
      "uid" : "c533f0d642a6f50e",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A6BFFD82B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1587152982558,
        "stop" : 1587152982558,
        "duration" : 0
      }
    }, {
      "uid" : "643007be73dcfa97",
      "status" : "passed",
      "time" : {
        "start" : 1587152162928,
        "stop" : 1587152211751,
        "duration" : 48823
      }
    }, {
      "uid" : "25b2b37748b8f807",
      "status" : "passed",
      "time" : {
        "start" : 1587147492387,
        "stop" : 1587147542295,
        "duration" : 49908
      }
    }, {
      "uid" : "97b757111b19ec15",
      "status" : "passed",
      "time" : {
        "start" : 1587133469370,
        "stop" : 1587133556006,
        "duration" : 86636
      }
    }, {
      "uid" : "bdbd4182566babd3",
      "status" : "passed",
      "time" : {
        "start" : 1587125633882,
        "stop" : 1587125689290,
        "duration" : 55408
      }
    }, {
      "uid" : "c83224531a065ac1",
      "status" : "passed",
      "time" : {
        "start" : 1587123458446,
        "stop" : 1587123494194,
        "duration" : 35748
      }
    }, {
      "uid" : "4c6395d1c42b1487",
      "status" : "passed",
      "time" : {
        "start" : 1587043880104,
        "stop" : 1587043923897,
        "duration" : 43793
      }
    }, {
      "uid" : "e4db8940b66aa2f2",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.TimeoutException: Message:",
      "time" : {
        "start" : 1587039908192,
        "stop" : 1587039959231,
        "duration" : 51039
      }
    }, {
      "uid" : "fa5d91b2a1d9aa48",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.TimeoutException: Message:",
      "time" : {
        "start" : 1587037348794,
        "stop" : 1587037399885,
        "duration" : 51091
      }
    }, {
      "uid" : "7e729200d7838d9b",
      "status" : "passed",
      "time" : {
        "start" : 1587030395435,
        "stop" : 1587030431762,
        "duration" : 36327
      }
    }, {
      "uid" : "3d1ad73c9c83a54",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command.",
      "time" : {
        "start" : 1587022509619,
        "stop" : 1587022534169,
        "duration" : 24550
      }
    }, {
      "uid" : "2de7e12ea06f8e24",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command.",
      "time" : {
        "start" : 1587018973701,
        "stop" : 1587018997058,
        "duration" : 23357
      }
    }, {
      "uid" : "9704d16c32a545b6",
      "status" : "passed",
      "time" : {
        "start" : 1587014326327,
        "stop" : 1587014431632,
        "duration" : 105305
      }
    }, {
      "uid" : "9ab17ed7b2b0b7cc",
      "status" : "passed",
      "time" : {
        "start" : 1587011066428,
        "stop" : 1587011180010,
        "duration" : 113582
      }
    }, {
      "uid" : "c02754ab375bb477",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command.",
      "time" : {
        "start" : 1587008320104,
        "stop" : 1587008342334,
        "duration" : 22230
      }
    }, {
      "uid" : "f153d3109bacd09c",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000012296A8E7B8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1587005940251,
        "stop" : 1587005940251,
        "duration" : 0
      }
    }, {
      "uid" : "4c55cc0fb2bec4ef",
      "status" : "passed",
      "time" : {
        "start" : 1586507402226,
        "stop" : 1586507484219,
        "duration" : 81993
      }
    }, {
      "uid" : "9ea3831f325eeb24",
      "status" : "failed",
      "statusDetails" : "AssertionError: assert False == True\n  -False\n  +True",
      "time" : {
        "start" : 1586158277082,
        "stop" : 1586158693456,
        "duration" : 416374
      }
    }, {
      "uid" : "c5b12503e2d97c9e",
      "status" : "passed",
      "time" : {
        "start" : 1586146520800,
        "stop" : 1586146570661,
        "duration" : 49861
      }
    } ],
    "categories" : [ ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 7,
        "skipped" : 0,
        "passed" : 21,
        "unknown" : 0,
        "total" : 28
      },
      "items" : [ {
        "uid" : "e1ca954021d40a6b",
        "reportUrl" : "http://192.168.88.58:8080/job/Timing/52/allure/#testresult/e1ca954021d40a6b",
        "status" : "passed",
        "time" : {
          "start" : 1587459321964,
          "stop" : 1587459365480,
          "duration" : 43516
        }
      }, {
        "uid" : "ee125e6e07b2ebfb",
        "reportUrl" : "http://192.168.88.58:8080/job/Timing/51/allure/#testresult/ee125e6e07b2ebfb",
        "status" : "passed",
        "time" : {
          "start" : 1587261631392,
          "stop" : 1587261671158,
          "duration" : 39766
        }
      }, {
        "uid" : "4c07474b2ed8e9fb",
        "reportUrl" : "http://192.168.88.58:8080/job/Timing/49/allure/#testresult/4c07474b2ed8e9fb",
        "status" : "passed",
        "time" : {
          "start" : 1587153779683,
          "stop" : 1587153832313,
          "duration" : 52630
        }
      }, {
        "uid" : "2d6bc84cb67d8347",
        "reportUrl" : "http://192.168.88.58:8080/job/Timing/48/allure/#testresult/2d6bc84cb67d8347",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A6BFFD82B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
        "time" : {
          "start" : 1587152982558,
          "stop" : 1587152982558,
          "duration" : 0
        }
      }, {
        "uid" : "d60402b951e03b6",
        "reportUrl" : "http://192.168.88.58:8080/job/Timing/46/allure/#testresult/d60402b951e03b6",
        "status" : "passed",
        "time" : {
          "start" : 1587152162928,
          "stop" : 1587152211751,
          "duration" : 48823
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "15d8c067758d6dfd.json",
  "parameterValues" : [ ]
}